18-authorization-authentication/votes_for_goats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # resources :goats, only: [:index, :show, :new, :create, :edit, :update]
  # resources :goats, except: [:destroy]
  resources :goats
  resources :votes, only: [:new, :create]
  resources :users, only: [:show, :index, :new, :create]

  patch "/sessions/reset", to: "sessions#reset_counter", as: "reset_session"
  delete "/sessions/logout", to: "sessions#destroy", as: "log_out_session"

  get "/sessions/login", to: "sessions#new", as: "new_login"
  post "/sessions/login", to: "sessions#create"
  # patch "/sessions", to: "sessions#update", as: "edit_session"

  # get '/goats', to: 'goats#index', as: 'goats'
  # get '/goats/:id', to: 'goats#show', as: 'goat'
  # get '/goats/new', to: 'goats#new', as: 'new_goat'
  # post '/goats', to: 'goats#create'
end

18-authorization-authentication/votes_for_goats/app/models/goat.rb
class Goat < ApplicationRecord
  has_many :votes 
  has_many :users, through: :votes

  # goat name must be unique
  validates :name, uniqueness: true
  # goat age must be over 18
  validates :age, numericality: {greater_than_or_equal_to: 18}
  #validation occupation must not be nill
  validates :occupation, :name, presence: true
  
  
  validate :name_can_not_be_greg

  def name_can_not_be_greg
    if self.name && self.name == 'greg'
      self.errors.add(:name, "Can not have my name!!!")
    end 
  end 


  def total_likes
    self.votes.count
  end 
end

18-authorization-authentication/votes_for_goats/app/models/user.rb
class User < ApplicationRecord
  has_many :votes 
  has_many :goats, through: :votes

  has_secure_password

  # def password=(secret)
  #   hash_pass = BCrypt::Password.create(secret)
  #   self.password_digest = hash_pass
  # end 

  # def password
  # end 
end

18-authorization-authentication/votes_for_goats/app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :goat
end

18-authorization-authentication/votes_for_goats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_user
  before_action :authenticate_user

  def set_user
    @current_user = User.find_by(id: session[:user_id])
  end 

  def authenticate_user
    if @current_user
      #continue working
    else 
      redirect_to new_login_path
    end 
  end 



end

18-authorization-authentication/votes_for_goats/app/controllers/goats_controller.rb
class GoatsController < ApplicationController
  before_action :find_goat, only: [:show, :edit, :update, :destroy]

  def index 
    @goats = Goat.all
    # render :index
  end

  def show 
    session[:page_counter] ||= 3
    session[:page_counter] = session[:page_counter].to_i - 1

    # cookies[:page_counter] ||= 3
    # cookies[:page_counter] = cookies[:page_counter].to_i - 1

    # if cookies[:page_counter]
    #   cookies[:page_counter] = cookies[:page_counter].to_i - 1
    # else 
    #   cookies[:page_counter] = 3
    # end 

    # @goat = Goat.find(params[:id])
    # render :show
  end 

  def new 
    @goat = Goat.new
    
    # render :new
  end 

  def create 
    @goat = Goat.new(goat_params(:age, :name))
    # @goat = Goat.create(goat_params)
    # if @goat.valid?
    if @goat.save 
      redirect_to goat_path(@goat)
    else
      #  get error messages
      flash[:errors] = @goat.errors.full_messages # returns an array
      # display the new form
      redirect_to new_goat_path
    end 
    # redirect_to goat
  end 

  def edit 
    # @goat = Goat.find(params[:id])
    # render :edit
  end 
  
  def update
    # @goat = Goat.find(params[:id])
    @goat.update(goat_params)

    # redirect_to goat_path(goat.id)
    redirect_to goat_path(@goat)
    # redirect_to goat
  end 

  def destroy 
    # @goat = Goat.find(params[:id])
    @goat.destroy 

    redirect_to goats_path
  end 

  private 

  def goat_params(*args)
    byebug
    params.require(:goat).permit(:name, :age, :occupation)
  end 

  def find_goat
    @goat = Goat.find(params[:id]) 
  end 

end

18-authorization-authentication/votes_for_goats/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user, only: [:new, :create]

  def reset_counter
    session[:page_counter] = 3
    redirect_back fallback_location: goats_path
  end 

  def new 
  end 

  def create
    @user = User.find_by(name: params[:session][:name])
  
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else 
      flash[:error] = "Username or Password not right"
      redirect_to new_login_path
    end 
  end 

  def destroy
    session[:user_id] = nil
    # session.delete(:user_id)

    redirect_to users_path
  end 
end 

18-authorization-authentication/votes_for_goats/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: [:new, :create, :index]

  def index 
    @users = User.all
  end 

  def show 
    @user = User.find(params[:id])
    if @user == @current_user
      render :show 
    else
      flash[:error] = "Gotta be your own page"
      redirect_to users_path 
    end 

  end 

  def new 
    @user = User.new 
  end 

  def create
    user = User.create(user_params)

    if user.valid?
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:errors] = user.errros.full_messages
      redirect_to new_user_path 
    end 

  end 

  private 

  def user_params
    params.require(:user).permit(:name, :password)
  end 
end

18-authorization-authentication/votes_for_goats/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def new 
    @vote = Vote.new
    @goats = Goat.all
    @users = User.all
    
    render :new
  end 

  def create 
    vote = Vote.create(vote_params)

    redirect_to user_path(vote.user)
  end 

  private 

  def vote_params
    params.require(:vote).permit(:user_id, :goat_id, :content)
  end 
end

18-authorization-authentication/votes_for_goats/app/helpers/application_helper.rb
module ApplicationHelper
end

18-authorization-authentication/votes_for_goats/app/helpers/goats_helper.rb
module GoatsHelper
end

18-authorization-authentication/votes_for_goats/app/helpers/users_helper.rb
module UsersHelper
end

18-authorization-authentication/votes_for_goats/app/helpers/votes_helper.rb
module VotesHelper
end

18-authorization-authentication/votes_for_goats/app/views/goats/_form.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error|%>
    <p><%= error %></p>
  <% end%>
<% end %>

 <%= form_for @goat do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :age %>
    <%= f.number_field :age %>

    <%= f.label :occupation %>
    <%= f.text_field :occupation %>
    
    <%= f.submit %>
  <% end %>

18-authorization-authentication/votes_for_goats/app/views/goats/edit.html.erb
<div class="container">
  <h1>Edit GOAT</h1>

  <%= render 'form' %>

</div>

18-authorization-authentication/votes_for_goats/app/views/goats/index.html.erb
<div class='container'>
  <h1>Goats Index</h1>

  <div class="index-container">

    <% @goats.each do |goat| %>
      <div class='index-tile'>
        <h3><%= link_to goat.name, goat_path(goat.id) %></h3>
        <p><%= goat.occupation %></p>
         <img class='index-img' src="<%= goat.img_url %>" alt="<%goat.name%>">
         <%= button_to "DELET", goat_path(goat), method: :delete %>
      </div>
    <% end %>
    
  </div>

</div>

18-authorization-authentication/votes_for_goats/app/views/goats/new.html.erb
<div class="container">
  <h1>New GOAT</h1>

  <%= render 'form' %>
  
</div>

18-authorization-authentication/votes_for_goats/app/views/goats/show.html.erb
<% if session[:page_counter] > 0 %>
  <div class='container'>
    <h1>Show Page</h1>
    <h2 style="color: purple;">You have <%= session[:page_counter] %> views left until our site cashes in</h2>

    <h2><%= @goat.name %></h2>
    <p>Age: <%= @goat.age %></p>
    <p>Occupation: <%= @goat.occupation %></p>
    <p>Life Status: <%= @goat.living ? "ALIVE!!" : "History Remembers" %></p>

    <p>Total Likes: <%= @goat.total_likes %></p>

    <marquee direction='right' scrollamount='15'>
      <img class='show-img' src="<%= @goat.img_url %>" alt="<%@goat.name%>">
    </marquee>

    <hr>
    <%= link_to "INDEX PAGE", goats_path %>
    <br>
    <%= link_to "Edit this GOAT", edit_goat_path(@goat.id) %>
    <%# button_to "Edit this GOAT", edit_goat_path(@goat.id), method: :get %>

  </div>
<% else %>
  <iframe width="764" height="573" src="https://www.youtube.com/embed/0kYYiRmtMH4?list=PL0E12D3DB9229B41D" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

  <%= button_to "I promise I watched this amazing Advertisment", reset_session_path, method: :patch %>

<% end %>

18-authorization-authentication/votes_for_goats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VotesForGoats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   <div class='nav'>
      <img class='logo' src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTXvQcTQ4zgABpqOwFbN-9AZqK11xRNhpdatnlCpkaRSqxvr_dG&usqp=CAU" alt="goatlogo">
    </div>

      <ul>
        <li><%= link_to 'User Home', users_path %></li>
        <li><%= link_to 'Goat Home', goats_path %></li>
        <li><%= link_to 'New Goat', new_goat_path %></li>

        <% if @current_user %>
          <li class='right'>Welcome <%= @current_user.name %> </li>
          <li class='right'><%= link_to 'Log Out', log_out_session_path, method: :delete %></li>
        <% else %>
          <li class='right'><%= link_to 'Sign-up', new_user_path %></li>
          <li class='right'><%= link_to 'Log-in', new_login_path %></li>
        <% end %>
      </ul>

    <%= yield %>
  </body>
</html>

18-authorization-authentication/votes_for_goats/app/views/users/index.html.erb
<div class='container'>
  <% if flash[:error]%>
    <p><%= flash[:error] %></p>
  <% end %>
  <h1>User Index</h1>

  <div class="index-container">

    <% @users.each do |user| %>
      <div class='index-tile'>
        <h3><%= link_to user.name, user_path(user.id) %></h3>
         <img class='index-img' src="<%= user.img_url %>" alt="<%user.name%>">
      </div>
    <% end %>
    
  </div>

</div>

18-authorization-authentication/votes_for_goats/app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.submit %>
<% end %>

18-authorization-authentication/votes_for_goats/app/views/users/show.html.erb
<div class='container'>
  <h1>Show Page</h1>

  <h2><%= @user.name %></h2>

  <marquee direction='right' scrollamount='15'>
    <img class='show-img' src="<%= @user.img_url %>" alt="<%@user.name%>">
  </marquee>


  <hr>
  <%= link_to "INDEX PAGE", users_path %>
  <hr>
  <% @user.votes.each do |vote| %>
    <h4><%= vote.goat.name %></h4> 
    <p><%= vote.content %></p>
    <hr>
  <% end %>
</div>

18-authorization-authentication/votes_for_goats/app/views/votes/new.html.erb
<div class="container">
  <%= form_for @vote do |f| %>
    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, @users, :id, :name  %>

    <%= f.label :goat_id %>
    <%= f.collection_select :goat_id, @goats, :id, :name %>

    <%= f.submit %>
  <% end %>
</div>